### PR TITLE
Add flags to avoid string optimization

### PR DESCRIPTION
**Pull request by hmaarrfk**
Fixes: https://github.com/conda-forge/ctng-compiler-activation-feedstock/issues/63

Questions:
- [ ] Do we need this in the `FFLAGS`. I assumed so.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
I can't recall if cflags gets reused for the other vars and so we only need this there. 

I think @isuruf might have insight or we can consult the activation scripts.

**Comment by hmaarrfk** [comment]
A quick search of `CFLAGS` in https://github.com/hmaarrfk/ctng-compiler-activation-feedstock/blob/fno-merge-constants/recipe/activate-gfortran.sh#L88 reveals nothing.

**Comment by beckermr** [comment]
Right except that the Fortean compiler requires the c one maybe. In any case, duplicated flags are ugly but shouldn’t break anything I think.

**Pull request closed without merging**
