### PR TITLE
ENH remove final sysroot bits

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
@isuruf This is ready to merge!

**Comment by isuruf** [comment]
This would make older python packages not work as they don't have the `sysconfig*-conda-*` files.

**Comment by beckermr** [comment]
In https://github.com/conda-forge/ctng-compiler-activation-feedstock/pull/24#issuecomment-663893109 you said we should fix it in the python feedstock and then fix it here. I guess the second part of that was wrong. Closing.

**Pull request closed without merging**
