### PR TITLE
GCC 14.2

### PR DESCRIPTION
**Pull request by apmorton**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Attempting to bring in GCC 14.2 here - not sure why so much changed as a result of the rerender - does this look correct?

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin rerender

**Comment by apmorton** [comment]
@isuruf rerendering with `conda-build 24.7.1` seems to have done something (old conda-smithy wasn't required, can rerender with latest if needed).

**Comment by mattgodbolt** [comment]
Would love to get this merged: the gcc 14.1 clang breakage is affecting my builds currently. Appreciate the work you do here: thanks!

**Comment by isuruf** [comment]
Thanks

**Comment by mattgodbolt** [comment]
Thanks @isuruf and @apmorton !

**Pull request merged**
