### PR TITLE
Use more standard form of release flag in `MESON_ARGS`

### PR DESCRIPTION
**Pull request by h-vetinari**
There are two different ways to set up a release flag to meson, `--buildtype release`, and `-Dbuildtype=release`. Apparently the latter is more common; at least it's the recommended way in the [docs](https://mesonbuild.com/Builtin-options.html#details-for-buildtype).

Since meson-python will by default add `-Dbuildtype=release`, the fact that the compiler-activation does the other kind leads to a duplicate specification and forces us to strip it out again as follows (e.g. in [scipy](https://github.com/conda-forge/scipy-feedstock/blob/d5fd7f7982dc670786726344a98b57af35bc2b2c/recipe/build.sh#L15-L17), but affects all feedstocks using meson-python).
```
# meson-python already sets up a -Dbuildtype=release argument to meson, so
# we need to strip --buildtype out of MESON_ARGS or fail due to redundancy
MESON_ARGS_REDUCED="$(echo $MESON_ARGS | sed 's/--buildtype release //g')"
```

To avoid this, use the more common form of the flag.

PS. Stumbled over this old [PR](https://github.com/conda-forge/scipy-feedstock/pull/232#discussion_r1176272687), where this was discussed with @rgommers
PPS. Sister PR of https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/112

### CODE REVIEW

**Comment by isuruf** [comment]
This might break packages that does the opposite. So, it's not clear which one is better.

**Comment by h-vetinari** [comment]
> This might break packages that does the opposite. 

That's clear, though I think it'd be good to decide on one and try to be consistent.

> So, it's not clear which one is better.

Given that meson-python uses `-Dbuildtype` (not the conda-forge version, but upstream), and that the meson docs use this variant too, I think the balance tilts towards that.

**Comment by rgommers** [comment]
> Given that meson-python uses `-Dbuildtype` (not only the conda-forge version, but built-in upstream), and that the meson docs use this variant too, I think the balance tilts towards that.

I agree. This change is known to avoid a bunch of argparsing complexity. It is right for all Python packages. In case there are non-Python packages that have an explicit `--buildtype=release` in their `build.sh` script in conda-forge, you'll get a clear error:
```
ERROR: Got argument buildtype as both -Dbuildtype and --buildtype. Pick one.
```
You'll fix that once, which is a simple 1-line diff, and does not require argument parsing.

`meson-python` isn't only relevant here because it's getting more popular, but because it's an intermediate layer that adds the incompatible flag. Such a layer does not exist for other languages, so there isn't the opposite problem if we make the switch here to using `-Dbuildtype`.

**Comment by h-vetinari** [comment]
I'm adapting the changes [discussed](https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/112#issuecomment-2221984866) on the clang side into #121

**Pull request closed without merging**
