### PR TITLE
Fix libstdcxx-ng and libgcc-ng version constraint

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by beckermr — APPROVED** [review]
LGTM!

**Comment by beckermr** [comment]
cc @jakirkham @chrisburr @kkraus14

**Comment by jakirkham** [comment]
Sorry, but I think I missed something. Was this coming up in some other context previously?

**Comment by beckermr** [comment]
Oh sorry. I thought you were on the chat in the gitter compilers channel.

**Comment by jakirkham** [comment]
Ah I see [the thread]( https://gitter.im/conda-forge/conda-forge-compilers?at=62827f72d30b6b44ebef83c0 ). Thanks for the context 🙏

**Review by kkraus14 — APPROVED** [review]

**Comment by h-vetinari** [comment]
> Ah I see [the thread](https://gitter.im/conda-forge/conda-forge-compilers?at=62827f72d30b6b44ebef83c0). Thanks for the context 🙏

Was looking this up today and that gitter link doesn't work for me anymore after the transition to matrix. Here's an updated [link](https://matrix.to/#/!mpHBnFUDYYQiDVFmpM:gitter.im/$Tetb8paVblzlPunxWVzZmFP5i8tsgYRu54zaazxGFgA?via=gitter.im&via=matrix.org)

**Pull request merged**
